import { useQuery } from '@tanstack/react-query'
import { useSession, signIn } from 'next-auth/react'
import Head from 'next/head'
import Link from 'next/link'
import Layout from '../components/layout'
import supabaseWithJwt from '../utils/supabaseCreateClient'

export default function Home() {
  const { data: session } = useSession()

  const supabaseAccessToken = session?.supabaseAccessToken

  const { data, isLoading, isFetching } = useQuery({
    queryKey: ['notes', supabaseAccessToken],
    queryFn: async () => {
      const { data } = await supabaseWithJwt(supabaseAccessToken)
        .from('users')
        .select('*, categories(*, notes(*))')
      return data
    },
    refetchOnWindowFocus: false,
  })

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="pt-20">
          <h1 className="text-4xl font-extrabold tracking-tight text-center text-white ">
            Perfect app to freshen up your memories and keep your ideas flowing!
          </h1>
          <p className="mt-6 text-center text-slate-400">
            Point-Notes is a simple app that allows you to create a{' '}
            <span className="text-sky-400">bite-sized</span> and{' '}
            <span className="text-sky-400">easy to digest</span> notes.
          </p>
          {!session ? (
            <div className="flex justify-center mt-6 text-sm">
              <a
                onClick={(e) => {
                  e.preventDefault()
                  signIn('google', {
                    callbackUrl: 'http://localhost:3000/notes',
                  })
                }}
                className="flex items-center justify-center w-full h-12 px-6 text-sm font-semibold text-white rounded-lg shadow-sm cursor-pointer bg-sky-400"
              >
                Sign in
              </a>
            </div>
          ) : (
            <div className="flex justify-center mt-6 text-sm">
              <Link
                href="/notes"
                className="flex items-center justify-center w-full h-12 px-6 text-sm font-semibold text-white border rounded-lg shadow-sm cursor-pointer border-sky-400 border-1 bg-slate-900"
              >
                {"Let's go!"}
              </Link>
            </div>
          )}
        </div>
      </Layout>
    </>
  )
}
